version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://server:5000
      - API_BACKEND=server:5000  # For nginx proxy configuration
    volumes:
      - ./client/src:/app/src
    depends_on:
      - server
    networks:
      - travel-network

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/travelease
      - JWT_SECRET=TravelEase2025SecretKeyForJWTTokens987654321
    depends_on:
      - mongo
    networks:
      - travel-network
    volumes:
      - ./server:/app
      - /app/node_modules

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - travel-network

volumes:
  mongo-data:

networks:
  travel-network:
    driver: bridge