version: '3.8'

services:
  client:
    #image: anildoc143/travel_ease_website_v4:client
    build: 
      context: ./client
      args:
        - NODE_ENV=development
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - API_BACKEND=server:5000  # For nginx proxy configuration
    volumes:
      - ./client/src:/app/src
    depends_on:
      - server
      - n8n
    networks:
      - travel-network

  server:
    #image: anildoc143/travel_ease_website_v4:server
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://admin:admin@mongo:27017/travelease?authSource=admin
      - JWT_SECRET=TravelEase2025SecretKeyForJWTTokens987654321
    depends_on:
      - mongo
    networks:
      - travel-network
    volumes:
      - ./server:/app
      - /app/node_modules

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=travelease
    volumes:
      - mongo-data:/data/db
    networks:
      - travel-network

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_WEBHOOK_URL=http://localhost:5678
      - N8N_WEBHOOK_TEST_URL=http://localhost:5678/webhook/test-chat
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=UTC
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_CORS_ENABLE=true
      - N8N_CORS_ALLOWED_ORIGINS=*
      - NODE_ENV=development
      - N8N_LOG_LEVEL=debug
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - travel-network
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5678/healthz"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  mongo-data:
  n8n-data:

networks:
  travel-network:
    driver: bridge