version: '3.8'

services:
  client:
    #image: anildoc143/travel_ease_website_v4:client
    build: 
      context: ./client
      args:
        - NODE_ENV=development
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://server:5000
      - API_BACKEND=server:5000  # For nginx proxy configuration
    volumes:
      - ./client/src:/app/src
    depends_on:
      - server
    networks:
      - travel-network

  server:
    #image: anildoc143/travel_ease_website_v4:server
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://admin:admin@mongo:27017/travelease?authSource=admin
      - JWT_SECRET=TravelEase2025SecretKeyForJWTTokens987654321
    depends_on:
      - mongo
    networks:
      - travel-network
    volumes:
      - ./server:/app
      - /app/node_modules

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=travelease
    volumes:
      - mongo-data:/data/db
    networks:
      - travel-network

volumes:
  mongo-data:

networks:
  travel-network:
    driver: bridge