apiVersion: apps/v1
kind : Deployment
metadata: 
  name: client-deployment
  label: client_deploy
spec:
  selector: 
    matchLabels:
      app: client_d
  template:
    metadata:
      labels:
        app: client_d
    spec:
      containers:
      - name: client_cont
        image: 306630623026.dkr.ecr.us-east-1.amazonaws.com/dev/travel_ease:client_v1
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          valueFrom: 
            configMapKeyRef:
              name: client-config
              key: NODE_ENV
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: REACT_APP_API_URL
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 400m
            memory: 500Mi
        readinessPorbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
      imagePullSecrets:
      - name: ecr-cred
      