apiVersion: apps/v1
kind : Deployment
metadata: 
  name: client-deployment
spec:
  selector: 
    matchLabels:
      app: client-d
  template:
    metadata:
      labels:
        app: client-d
    spec:
      containers:
      - name: client
        image: anildoc143/travel_ease_website_v6:client
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          valueFrom: 
            configMapKeyRef:
              name: client-config
              key: NODE_ENV
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: REACT_APP_API_URL
        - name: API_BACKEND
          value: "server-service:80"  # Kubernetes service name and port
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
    #  imagePullSecrets:
    #  - name: ecr-cred
      
