apiVersion: v1
kind: Secret
metadata:
  name: ecr-cred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: $(echo '{"auths":{"306630623026.dkr.ecr.us-east-1.amazonaws.com":{"username":"AWS","password":"'$(aws ecr get-login-password --region us-east-1)'","auth":"'$(echo -n "AWS:$(aws ecr get-login-password --region us-east-1)" | base64 -w 0)'"}}}' | base64 -w 0)