apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-ease-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:  # No host specified - works with any IP/domain
      paths:
      # Only expose frontend - all requests go to React app
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 80
