apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: k8s.io/minikube-hostpath  # For minikube
parameters:
  type: DirectoryOrCreate
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
