apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-replica-set-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mongo-init
        image: mongo:5.0
        command:
        - "bash"
        - "/scripts/init-replica-set.sh"
        volumeMounts:
        - name: init-script
          mountPath: /scripts
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
      volumes:
      - name: init-script
        configMap:
          name: mongo-init-script
          defaultMode: 0755
