apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ ..Release.Name}}
spec:
  replicas: 1  # Single instance for testing
  serviceName: "mongo"
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:      
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image }}:{{ .Values.mongo.tag }}"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: MONGO_INITDB_DATABASE
          value: "travelease"
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        resources:
          requests:
            cpu: 100m  # Reduced for Minikube
            memory: 128Mi  # Reduced for Minikube
          limits:
            cpu: 200m  # Reduced for Minikube
            memory: 256Mi  # Reduced for Minikube
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "minikube-storage"  # Use Minikube storage class
      resources:
        requests:
          storage: 1Gi
