apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init-replica-set.sh: |
    #!/bin/bash
    set -e
    
    echo "Waiting for MongoDB primary to be ready..."
    until mongosh --host mango-statefulset-0.mongo-headless:27017 --eval "db.runCommand('ping').ok" --quiet; do
      echo "Waiting for MongoDB primary..."
      sleep 5
    done
    
    echo "Waiting for all MongoDB pods to be ready..."
    until mongosh --host mango-statefulset-1.mongo-headless:27017 --eval "db.runCommand('ping').ok" --quiet; do
      echo "Waiting for MongoDB secondary 1..."
      sleep 5
    done
    
    until mongosh --host mango-statefulset-2.mongo-headless:27017 --eval "db.runCommand('ping').ok" --quiet; do
      echo "Waiting for MongoDB secondary 2..."
      sleep 5
    done
    
    echo "Checking replica set status with authentication..."
    # Check if we can connect with admin credentials (means replica set is initialized)
    if mongosh --host mango-statefulset-0.mongo-headless:27017 -u admin -p admin --authenticationDatabase admin --eval "rs.status().ok" --quiet 2>/dev/null; then
      echo "Replica set already initialized and admin user exists."
    else
      echo "Replica set initialization or admin user creation may be needed."
      echo "This should be handled by the primary pod's startup script."
    fi
    
    echo "Final replica set status check..."
    mongosh --host mango-statefulset-0.mongo-headless:27017 -u admin -p admin --authenticationDatabase admin --eval "
      print('Replica Set Status:');
      printjson(rs.status());
      print('\\nReplica Set Configuration:');
      printjson(rs.conf());
    " --quiet || echo "Unable to connect with admin credentials yet. This is normal during initialization."
