apiVersion: v1
kind: Service
metadata:
  name: mongo-primary
spec:
  selector:
    app: db
    # This will typically route to the primary replica
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
