apiVersion: v1
kind: Service
metadata:
  name: mongo-headless  # This matches the serviceName in StatefulSet
spec:
  selector:
    app: db
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: 27017
      targetPort: 27017
