apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init-replica-set.sh: |
    #!/bin/bash
    set -e
    
    echo "Waiting for MongoDB to be ready..."
    until mongosh --host mango-statefulset-0.mongo-headless:27017 --eval "db.runCommand('ping').ok" --quiet; do
      echo "Waiting for MongoDB..."
      sleep 5
    done
    
    echo "Checking if replica set is already initialized..."
    RS_STATUS=$(mongosh --host mango-statefulset-0.mongo-headless:27017 --eval "try { rs.status().ok } catch(e) { 0 }" --quiet)
    
    if [ "$RS_STATUS" != "1" ]; then
      echo "Initializing replica set..."
      mongosh --host mango-statefulset-0.mongo-headless:27017 --eval "
        rs.initiate({
          _id: 'rs0',
          members: [
            { _id: 0, host: 'mango-statefulset-0.mongo-headless:27017', priority: 2 },
            { _id: 1, host: 'mango-statefulset-1.mongo-headless:27017', priority: 1 },
            { _id: 2, host: 'mango-statefulset-2.mongo-headless:27017', priority: 1 }
          ]
        })
      "
      
      echo "Waiting for replica set to be ready..."
      until mongosh --host mango-statefulset-0.mongo-headless:27017 --eval "rs.status().members.length == 3" --quiet; do
        sleep 5
      done
      
      echo "Creating admin user..."
      mongosh --host mango-statefulset-0.mongo-headless:27017 --eval "
        db.getSiblingDB('admin').createUser({
          user: 'admin',
          pwd: 'admin',
          roles: [{role: 'root', db: 'admin'}]
        })
      "
      
      echo "Replica set initialization complete!"
    else
      echo "Replica set already initialized."
    fi
