apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-simple
data:
  init-mongo.sh: |
    #!/bin/bash
    set -e
    
    # Start MongoDB without authentication for initial setup
    mongod --replSet rs0 --bind_ip_all --dbpath /data/db &
    MONGO_PID=$!
    
    # Wait for MongoDB to start
    echo "Waiting for MongoDB to start..."
    until mongosh --eval "db.runCommand('ping').ok" --quiet; do
      sleep 2
    done
    
    # Initialize replica set
    echo "Initializing replica set..."
    mongosh --eval "
      rs.initiate({
        _id: 'rs0',
        members: [
          { _id: 0, host: 'mango-statefulset-0.mongo-headless:27017' }
        ]
      })
    "
    
    # Wait for replica set to be primary
    echo "Waiting for this node to become primary..."
    until mongosh --eval "db.isMaster().ismaster" --quiet | grep -q true; do
      sleep 2
    done
    
    # Create admin user
    echo "Creating admin user..."
    mongosh --eval "
      db.getSiblingDB('admin').createUser({
        user: '$MONGO_INITDB_ROOT_USERNAME',
        pwd: '$MONGO_INITDB_ROOT_PASSWORD',
        roles: [{role: 'root', db: 'admin'}]
      })
    "
    
    # Add other members to replica set
    echo "Adding other members to replica set..."
    mongosh --eval "
      rs.add('mango-statefulset-1.mongo-headless:27017');
      rs.add('mango-statefulset-2.mongo-headless:27017');
    "
    
    echo "Replica set initialization complete!"
    
    # Stop MongoDB
    kill $MONGO_PID
    wait $MONGO_PID
    
    # Start MongoDB with authentication
    echo "Starting MongoDB with authentication..."
    exec mongod --replSet rs0 --bind_ip_all --auth --keyFile /tmp/keyfile --dbpath /data/db
