apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-replica-set-add-members
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mongo-add-members
        image: mongo:5.0
        command:
        - "bash"
        - "-c"
        - |
          set -e
          
          echo "Waiting for all MongoDB pods to be ready..."
          
          # Wait for primary
          until mongosh --host mango-statefulset-0.mongo-headless:27017 -u admin -p admin --authenticationDatabase admin --eval "db.runCommand('ping').ok" --quiet; do
            echo "Waiting for primary..."
            sleep 5
          done
          
          # Wait for secondaries
          until mongosh --host mango-statefulset-1.mongo-headless:27017 --eval "db.runCommand('ping').ok" --quiet; do
            echo "Waiting for secondary 1..."
            sleep 5
          done
          
          echo "Adding member to replica set..."
          mongosh --host mango-statefulset-0.mongo-headless:27017 -u admin -p admin --authenticationDatabase admin --eval "
            try {
              rs.add('mango-statefulset-1.mongo-headless:27017');
              print('Added member 1');
            } catch(e) {
              print('Member 1 already exists or error: ' + e);
            }
            
            print('Final replica set status:');
            printjson(rs.status());
          "
          
          echo "Replica set setup complete!"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
