# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: mongo-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: gp3
#   hostPath:
#     path: /data/mongo
#   volumeMode: Filesystem
