---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-server-secret"
type: Opaque
data:
  NODE_ENV: {{ b64enc "development" }}
  MONGO_URI: {{ printf "mongodb://admin:admin@%s-mongo-service:27017/travelease?authSource=admin" .Release.Name | b64enc }}
  JWT_SECRET: {{ b64enc "TravelEase2025SecretKeyForJWTTokens987654321" }}
