apiVersion: apps/v1
kind : Deployment
metadata: 
  name: server-deployment
spec:
  selector: 
    matchLabels:
      app: server-d
  template:
    metadata:
      labels:
        app: server-d
    spec:
      containers:
      - name: server
        image: 306630623026.dkr.ecr.us-east-1.amazonaws.com/dev/travel_ease:server_v1
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: NODE_ENV
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: MONGO_URI
        resources:
          requests:
            cpu: 200m
            memory: 254Mi
          limits:
            cpu: 700m
            memory: 812Mi
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
   #   imagePullSecrets:
    #  - name: ecr-cred
