apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "{{ .Release.Name }}-server"
spec:
  selector: 
    matchLabels:
      app: "{{ .Release.Name }}-server"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-server"
    spec:
      containers:
      - name: server
        image: "{{ .Values.server.image }}:{{ .Values.server.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-server-secret"
              key: NODE_ENV
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-server-secret"
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-server-secret"
              key: JWT_SECRET
        resources:
          requests:
            cpu: {{ .Values.resources.server.requests.cpu }}
            memory: {{ .Values.resources.server.requests.memory }}
          limits:
            cpu: {{ .Values.resources.server.limits.cpu }}
            memory: {{ .Values.resources.server.limits.memory }}
   #   imagePullSecrets:
    #  - name: ecr-cred
