apiVersion: apps/v1
kind : Deployment
metadata: 
  name: server-deployment
spec:
  selector: 
    matchLabels:
      app: server-d
  template:
    metadata:
      labels:
        app: server-d
    spec:
      containers:
      - name: server
        image: anildoc143/travel_ease_website:server_v1
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: NODE_ENV
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: MONGO_URI
        resources:
          requests:
            cpu: 200m
            memory: 254Mi
          limits:
            cpu: 700m
            memory: 812Mi
   #   imagePullSecrets:
    #  - name: ecr-cred
