---
apiVersion: v1
kind: Secret
metadata:
  name: server-secret
type: Opaque
data:
  NODE_ENV: ZGV2ZWxvcG1lbnQ=
  MONGO_URI: bW9uZ29kYjovL2FkbWluOmFkbWluQG1hbmdvLXN0YXRlZnVsc2V0LTAubW9uZ28taGVhZGxlc3M6MjcwMTcsbWFuZ28tc3RhdGVmdWxzZXQtMS5tb25nby1oZWFkbGVzczoyNzAxNyxtYW5nby1zdGF0ZWZ1bHNldC0yLm1vbmdvLWhlYWRsZXNzOjI3MDE3L3RyYXZlbGVhc2U/YXV0aFNvdXJjZT1hZG1pbiZyZXBsaWNhU2V0PXJzMA==
  JWT_SECRET: VHJhdmVsRWFzZTIwMjVTZWNyZXRLZXlGb3JKV1RUb2tlbnM5ODc2NTQzMjE=
