---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server_hpa
spec:
  serviceName: server-service
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70