apiVersion: apps/v1
kind : Deployment
metadata: 
  name: server-deployment
spec:
  selector: 
    matchLabels:
      app: server-d
  template:
    metadata:
      labels:
        app: server-d
    spec:
      containers:
      - name: server
        image: anildoc143/travel_ease_website_v5:server
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: NODE_ENV
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: JWT_SECRET
        resources:
          requests:
            cpu: 100m
            memory: 154Mi
          limits:
            cpu: 254m
            memory: 354Mi
   #   imagePullSecrets:
    #  - name: ecr-cred
