apiVersion: apps/v1
kind : Deployment
metadata: 
  name: {{.Release.Name}}
spec:
  selector: 
    matchLabels:
      app: server-d
  template:
    metadata:
      labels:
        app: server-d
    spec:
      containers:
      - name: server
        image: "{{ .Values.server.image }}:{{ .Values.server.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: NODE_ENV
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: JWT_SECRET
        resources:
          requests:
            cpu: 100m  # Reduced for Minikube
            memory: 128Mi  # Reduced for Minikube
          limits:
            cpu: 300m  # Reduced for Minikube
            memory: 256Mi  # Reduced for Minikube
   #   imagePullSecrets:
    #  - name: ecr-cred
