apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minikube-storage
provisioner: k8s.io/minikube-hostpath  # For Minikube
parameters:
  type: DirectoryOrCreate
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete  # Better for testing in Minikube
