kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp3 # Changed to match the storageClassName in mongo_statefulset.yml
provisioner: aws-ebs
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
